"""Build the frozen, stratified train/dev/test split for Model 1.

Deterministic (fixed SEED). Reads only from data/ and writes train.csv /
dev.csv / test.csv plus a split_report.md to data/processed/. Once committed,
this split must not change (MODEL_PLAN.md sections 2 and 6).

Steps, in order (order matters - section 7):
  1. keep labelled rows (Coursera only)
  2. map localised category labels to their English class
  3. deduplicate on Title + Short Intro
  4. stratified split, per class, with a fixed seed

Run from the repo root:  python scripts/make_split.py
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.data_contract import (  # noqa: E402
    COURSES_CSV,
    DATA_PROCESSED,
    DEDUP_KEYS,
    DEV_FRAC,
    LABEL_COL,
    LABEL_SITE,
    LOCALISED_LABEL_MAP,
    SEED,
    SPLIT_KEEP_COLS,
    TEST_FRAC,
)


def stratified_split(df: pd.DataFrame, label_col: str, seed: int):
    """Split each class independently so every split keeps the class mix.

    Small classes still get at least one row in dev and test where possible.
    Returns (train, dev, test) as DataFrames.
    """
    rng = np.random.default_rng(seed)
    train_parts, dev_parts, test_parts = [], [], []

    for _, group in df.groupby(label_col, sort=True):
        idx = group.index.to_numpy().copy()
        rng.shuffle(idx)
        n = len(idx)
        n_test = int(round(n * TEST_FRAC))
        n_dev = int(round(n * DEV_FRAC))
        # Guarantee train keeps at least one row for tiny classes.
        n_test = min(n_test, max(0, n - 2))
        n_dev = min(n_dev, max(0, n - 1 - n_test))

        test_parts.append(group.loc[idx[:n_test]])
        dev_parts.append(group.loc[idx[n_test:n_test + n_dev]])
        train_parts.append(group.loc[idx[n_test + n_dev:]])

    train = pd.concat(train_parts).sample(frac=1, random_state=seed)
    dev = pd.concat(dev_parts).sample(frac=1, random_state=seed)
    test = pd.concat(test_parts).sample(frac=1, random_state=seed)
    return train, dev, test


def class_distribution(df: pd.DataFrame) -> pd.Series:
    return df[LABEL_COL].value_counts().sort_index()


def main() -> None:
    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    courses = pd.read_csv(COURSES_CSV, low_memory=False)

    # 1. labelled rows only
    df = courses[courses["Site"] == LABEL_SITE].copy()
    n_labelled = len(df)

    # 2. map localised labels
    n_localised = int(df[LABEL_COL].isin(LOCALISED_LABEL_MAP).sum())
    df[LABEL_COL] = df[LABEL_COL].replace(LOCALISED_LABEL_MAP)

    # 3. deduplicate on course text (keep first occurrence)
    before = len(df)
    df = df.drop_duplicates(subset=DEDUP_KEYS, keep="first")
    n_dropped = before - len(df)

    # keep only the columns the split needs
    df = df[SPLIT_KEEP_COLS].reset_index(drop=True)

    # 4. stratified split
    train, dev, test = stratified_split(df, LABEL_COL, SEED)

    for name, part in [("train", train), ("dev", dev), ("test", test)]:
        part.to_csv(DATA_PROCESSED / f"{name}.csv", index=False, encoding="utf-8")

    # sha256 of each committed split file - the fingerprint the frozen-split
    # test checks against (tests/test_frozen_split.py).
    checksums = {
        f"{name}.csv": hashlib.sha256(
            (DATA_PROCESSED / f"{name}.csv").read_bytes()
        ).hexdigest()
        for name in ("train", "dev", "test")
    }

    # --- committed metadata (split_manifest.json, per sections 2 and 6) -----
    dist = pd.DataFrame({
        "train": class_distribution(train),
        "dev": class_distribution(dev),
        "test": class_distribution(test),
    }).fillna(0).astype(int)
    dist["total"] = dist.sum(axis=1)

    manifest = {
        "seed": SEED,
        "labelled_site": LABEL_SITE,
        "labelled_rows": int(n_labelled),
        "localised_labels_mapped": int(n_localised),
        "dedup_keys": DEDUP_KEYS,
        "duplicate_rows_dropped": int(n_dropped),
        "rows_after_dedup": int(len(df)),
        "columns_kept": SPLIT_KEEP_COLS,
        "split_sizes": {"train": int(len(train)), "dev": int(len(dev)), "test": int(len(test))},
        "class_distribution": {
            str(cat): {k: int(v) for k, v in row.items()} for cat, row in dist.iterrows()
        },
        "checksums_sha256": checksums,
    }
    (DATA_PROCESSED / "split_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    lines: list[str] = []
    lines.append("# Frozen split report\n")
    lines.append("_Generated by `scripts/make_split.py`. Do not edit by hand._\n")
    lines.append(f"- Seed: **{SEED}** (also in `data/processed/split_manifest.json`)")
    lines.append(f"- Labelled rows ({LABEL_SITE}): {n_labelled:,}")
    lines.append(f"- Localised category labels mapped to English: {n_localised}")
    lines.append(f"- Duplicate rows dropped on `{' + '.join(DEDUP_KEYS)}`: {n_dropped:,}")
    lines.append(f"- Rows after dedup: **{len(df):,}**")
    lines.append(f"- Split sizes - train **{len(train):,}** / dev **{len(dev):,}** / "
                 f"test **{len(test):,}**")
    lines.append(f"- Columns kept: {', '.join(SPLIT_KEEP_COLS)}\n")

    lines.append("## Class distribution per split\n")
    lines.append("| Category | Train | Dev | Test | Total |")
    lines.append("|---|---|---|---|---|")
    for cat, row in dist.iterrows():
        lines.append(f"| {cat} | {row['train']} | {row['dev']} | {row['test']} | {row['total']} |")
    lines.append(f"| **All** | **{len(train)}** | **{len(dev)}** | **{len(test)}** | "
                 f"**{len(df)}** |\n")

    (DATA_PROCESSED / "split_report.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote train/dev/test.csv, split_manifest.json and split_report.md to {DATA_PROCESSED}")
    print(f"  {n_labelled:,} labelled -> {len(df):,} after dedup "
          f"({n_dropped:,} dupes dropped, {n_localised} localised labels mapped)")
    print(f"  train {len(train):,} / dev {len(dev):,} / test {len(test):,}")


if __name__ == "__main__":
    main()
