"""Profile the raw data and reproduce the Model-2 exact-match finding.

Reads only from data/ (read-only) and writes a human-readable report plus a
machine-readable JSON to data/processed/. Every number the report cites comes
from this script, so it can be cited instead of a notebook cell
(MODEL_PLAN.md sections 4, 5, 7).

Run from the repo root:  python scripts/profile_data.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.data_contract import (  # noqa: E402
    COURSES_CSV,
    DATA_PROCESSED,
    DEDUP_KEYS,
    ENGLISH_CATEGORIES,
    ESCO_SKILLS_FULL_CSV,
    LABEL_COL,
    LABEL_SITE,
    LOCALISED_LABEL_MAP,
)

KEY_COLS = ["Title", "Short Intro", "Category", "Skills", "URL"]


def split_skill_strings(series: pd.Series) -> set[str]:
    """Distinct, lowercased skill strings from the free-text Skills column."""
    vocab: set[str] = set()
    for cell in series.dropna():
        for part in str(cell).replace("\n", ",").split(","):
            token = part.strip().lower()
            if token:
                vocab.add(token)
    return vocab


def esco_label_set(esco: pd.DataFrame) -> set[str]:
    """Lowercased ESCO preferredLabel + altLabels (newline-separated)."""
    labels: set[str] = set()
    labels.update(esco["preferredLabel"].dropna().str.lower())
    for cell in esco["altLabels"].dropna():
        for alt in str(cell).split("\n"):
            alt = alt.strip().lower()
            if alt:
                labels.add(alt)
    return labels


def main() -> None:
    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    courses = pd.read_csv(COURSES_CSV, low_memory=False)
    esco = pd.read_csv(ESCO_SKILLS_FULL_CSV, low_memory=False)

    stats: dict = {}

    # --- Courses: shape, fill rates, labels --------------------------------
    stats["courses_rows"] = int(len(courses))
    stats["courses_cols"] = int(courses.shape[1])
    stats["fill_rates"] = {
        col: round(float(courses[col].notna().mean()), 4) for col in KEY_COLS
    }

    labelled = courses[courses["Site"] == LABEL_SITE]
    stats["labelled_site"] = LABEL_SITE
    stats["labelled_rows"] = int(len(labelled))

    cat_counts = labelled[LABEL_COL].value_counts(dropna=False)
    stats["category_counts_raw"] = {str(k): int(v) for k, v in cat_counts.items()}
    stats["localised_label_rows"] = int(
        labelled[LABEL_COL].isin(LOCALISED_LABEL_MAP).sum()
    )
    stats["n_english_categories"] = len(ENGLISH_CATEGORIES)

    # --- Duplicates (the leakage risk in section 7) ------------------------
    stats["dup_url_rows"] = int(courses.duplicated(subset=["URL"]).sum())
    stats["dup_text_rows"] = int(courses.duplicated(subset=DEDUP_KEYS).sum())

    # --- Model-2 exact-match baseline (the section 4 finding) --------------
    vocab = split_skill_strings(courses["Skills"])
    esco_labels = esco_label_set(esco)
    matched = sum(1 for v in vocab if v in esco_labels)
    stats["distinct_course_skill_strings"] = len(vocab)
    stats["esco_label_set_size"] = len(esco_labels)
    stats["exact_matched_strings"] = matched
    stats["exact_match_rate"] = round(matched / len(vocab), 4) if vocab else 0.0
    stats["unmatched_rate"] = round(1 - stats["exact_match_rate"], 4)

    # --- Write JSON --------------------------------------------------------
    json_path = DATA_PROCESSED / "profile_stats.json"
    json_path.write_text(json.dumps(stats, indent=2, ensure_ascii=False), encoding="utf-8")

    # --- Write Markdown report --------------------------------------------
    lines: list[str] = []
    lines.append("# Data profile\n")
    lines.append("_Generated by `scripts/profile_data.py`. Do not edit by hand._\n")

    lines.append("## Course catalogue\n")
    lines.append(f"- Rows: **{stats['courses_rows']:,}**, columns: {stats['courses_cols']}")
    lines.append(f"- Labelled rows ({LABEL_SITE} only): **{stats['labelled_rows']:,}**")
    lines.append(f"- Canonical English categories: {stats['n_english_categories']}")
    lines.append(f"- Rows with a localised category label (mapped, not dropped): "
                 f"{stats['localised_label_rows']}\n")

    lines.append("### Fill rates (key columns)\n")
    lines.append("| Column | Fill rate |")
    lines.append("|---|---|")
    for col, rate in stats["fill_rates"].items():
        lines.append(f"| {col} | {rate:.1%} |")
    lines.append("")

    lines.append("### Category distribution (labelled rows)\n")
    lines.append("| Category | Count |")
    lines.append("|---|---|")
    for cat, n in stats["category_counts_raw"].items():
        lines.append(f"| {cat} | {n} |")
    lines.append("")

    lines.append("## Duplicate rows (split-leakage risk)\n")
    lines.append(f"- Duplicate `URL` rows: **{stats['dup_url_rows']:,}**")
    lines.append(f"- Duplicate `{' + '.join(DEDUP_KEYS)}` rows: "
                 f"**{stats['dup_text_rows']:,}** &larr; dedup on this before splitting\n")

    lines.append("## Model 2 - exact-match baseline\n")
    lines.append(f"- Distinct course skill strings: **{stats['distinct_course_skill_strings']:,}**")
    lines.append(f"- ESCO label set (preferred + alt, lowercased): "
                 f"{stats['esco_label_set_size']:,}")
    lines.append(f"- Exact-matched: **{stats['exact_matched_strings']:,}** "
                 f"(**{stats['exact_match_rate']:.1%}**)")
    lines.append(f"- **Unmatched: {stats['unmatched_rate']:.1%}** - the empirical argument "
                 "for a model over a lookup table.\n")

    (DATA_PROCESSED / "profile_report.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {json_path.name} and profile_report.md to {DATA_PROCESSED}")
    print(f"  labelled rows: {stats['labelled_rows']:,} | "
          f"dup(text): {stats['dup_text_rows']:,} | "
          f"exact-match: {stats['exact_match_rate']:.1%} "
          f"(unmatched {stats['unmatched_rate']:.1%})")


if __name__ == "__main__":
    main()
